tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-dim": "#f47785",
                "tertiary-fixed": "#d697ff",
                "on-surface": "#ffffff",
                "surface-container-highest": "#262626",
                "on-tertiary-fixed": "#2a0044",
                "primary-fixed-dim": "#ff5b47",
                "surface-tint": "#ff8e7d",
                "surface-container": "#191919",
                "primary-container": "#ff7763",
                "surface-container-high": "#1f1f1f",
                "outline-variant": "#484848",
                "surface-dim": "#0e0e0e",
                "outline": "#757575",
                "tertiary": "#dba2ff",
                "on-tertiary": "#53157a",
                "on-primary-fixed-variant": "#600000",
                "surface-variant": "#262626",
                "secondary-container": "#842133",
                "on-secondary-fixed": "#6a0c22",
                "tertiary-container": "#d191fa",
                "surface-bright": "#2c2c2c",
                "on-primary-fixed": "#000000",
                "error-dim": "#d73357",
                "on-primary": "#650000",
                "inverse-on-surface": "#555555",
                "surface-container-low": "#131313",
                "tertiary-dim": "#c384eb",
                "on-secondary": "#570017",
                "background": "#0e0e0e",
                "surface-container-lowest": "#000000",
                "on-secondary-container": "#ffc0c4",
                "secondary-fixed-dim": "#ffaeb4",
                "secondary": "#fe7e8c",
                "primary-fixed": "#ff7763",
                "on-error-container": "#ffb2b9",
                "on-background": "#ffffff",
                "on-tertiary-container": "#47026f",
                "inverse-primary": "#c10100",
                "primary-dim": "#eb0000",
                "primary": "#ff8e7d",
                "inverse-surface": "#f9f9f9",
                "on-tertiary-fixed-variant": "#56197d",
                "on-error": "#490013",
                "on-secondary-fixed-variant": "#912b3c",
                "error-container": "#a70138",
                "on-surface-variant": "#ababab",
                "tertiary-fixed-dim": "#c889f1",
                "surface": "#0e0e0e",
                "secondary-fixed": "#ffc2c6",
                "error": "#ff6e84",
                "on-primary-container": "#4f0000"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "sora": ["Sora", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};
