tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-dim": "#cc0000",
                "tertiary-fixed": "#ff3333",
                "on-surface": "#ffffff",
                "surface-container-highest": "#1a1a1a",
                "on-tertiary-fixed": "#000000",
                "primary-fixed-dim": "#ff0000",
                "surface-tint": "#ff0000",
                "surface-container": "#0c0c0c",
                "primary-container": "#cc0000",
                "surface-container-high": "#121212",
                "outline-variant": "#333333",
                "surface-dim": "#050505",
                "outline": "#666666",
                "tertiary": "#ff3333",
                "on-tertiary": "#000000",
                "on-primary-fixed-variant": "#440000",
                "surface-variant": "#111111",
                "secondary-container": "#880000",
                "on-secondary-fixed": "#000000",
                "tertiary-container": "#ff0000",
                "surface-bright": "#1a1a1a",
                "on-primary-fixed": "#ffffff",
                "error-dim": "#ff0000",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#aaaaaa",
                "surface-container-low": "#080808",
                "tertiary-dim": "#ff4444",
                "on-secondary": "#ffffff",
                "background": "#000000",
                "surface-container-lowest": "#000000",
                "on-secondary-container": "#ffaaaa",
                "secondary-fixed-dim": "#ff0000",
                "secondary": "#ff0000",
                "primary-fixed": "#ff0000",
                "on-error-container": "#ffffff",
                "on-background": "#ffffff",
                "on-tertiary-container": "#000000",
                "inverse-primary": "#880000",
                "primary-dim": "#ff0000",
                "primary": "#ff0000",
                "inverse-surface": "#ffffff",
                "on-tertiary-fixed-variant": "#440000",
                "on-error": "#ffffff",
                "on-secondary-fixed-variant": "#440000",
                "error-container": "#ff0000",
                "on-surface-variant": "#cccccc",
                "tertiary-fixed-dim": "#ff6666",
                "surface": "#000000",
                "secondary-fixed": "#ff4444",
                "error": "#ff0000",
                "on-primary-container": "#ffffff"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "sora": ["Sora", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};

